---
:sshPrivateKeyPath: ./tmp/DemandCubePlaybooks/roles/teamaccess/files/teamaccess
:digitalOceanToken: 4af329d2baa4686af5ef372006389680197d1be905db948043679961a050b3ad
:intnetName: neverwinterDP
machines:
- name: genericVF
  ram: 512MB
  digitalOceanRegion: nyc2
- name: elasticsearchVF
  ram: 512MB
  digitalOceanRegion: nyc2
- name: zookeeperVF
  ram: 512MB
  digitalOceanRegion: nyc2
- name: kafkaVF
  ram: 512MB
  digitalOceanRegion: nyc2
- name: sparknginVF
  ram: 512MB
  digitalOceanRegion: nyc2
- name: ringbearerVF
  ram: 512MB
  digitalOceanRegion: nyc2
